import { DoomActions, Sides, Sky, SkyActions } from 'models/types';

export const Sky1: Readonly<Record<Sides, Sky>> = Object.freeze({
  [Sides.A]: {
    doom: [],
    science: [3, 1, 3, 1],
    horizon: [
      { action: SkyActions.AAZ, aaForce: 3, line: 0 },
      { action: SkyActions.MR, line: 0 },
      { action: SkyActions.N, line: 0 },
      { action: SkyActions.MSD, line: 0 },
      { action: SkyActions.N, line: 0 },
      { action: SkyActions.N, line: 1 },
      { action: SkyActions.AAZ, aaForce: 6, line: 1 },
      { action: SkyActions.N, line: 1 },
      { action: SkyActions.ML, line: 1 },
      { action: SkyActions.AAZ, aaForce: 4, line: 1 },
      { action: SkyActions.MR, line: 2 },
      { action: SkyActions.N, line: 2 },
      { action: SkyActions.AAZ, aaForce: 3, line: 2 },
      { action: SkyActions.N, line: 2 },
      { action: SkyActions.ML, line: 2 },
      { action: SkyActions.N, line: 3 },
      { action: SkyActions.AAZ, aaForce: 5, line: 3 },
      { action: SkyActions.MSD, line: 3 },
      { action: SkyActions.AAZ, aaForce: 4, line: 3 },
      { action: SkyActions.N, line: 3 },
    ],
  } as Sky,
  [Sides.B]: {
    doom: [],
    science: [3, 2, 1, 5],
    horizon: [
      { action: SkyActions.MSD, line: 0 },
      { action: SkyActions.AAZ, aaForce: 5, line: 0 },
      { action: SkyActions.MSD, line: 0 },
      { action: SkyActions.N, line: 0 },
      { action: SkyActions.ML, line: 0 },
      { action: SkyActions.N, line: 1 },
      { action: SkyActions.N, line: 1 },
      { action: SkyActions.AAZ, aaForce: 4, line: 1 },
      { action: SkyActions.MSD, line: 1 },
      { action: SkyActions.AAZ, aaForce: 5, line: 1 },
      { action: SkyActions.AAZ, aaForce: 4, line: 2 },
      { action: SkyActions.MSD, line: 2 },
      { action: SkyActions.N, line: 2 },
      { action: SkyActions.AAZ, aaForce: 6, line: 2 },
      { action: SkyActions.MSD, line: 2 },
      { action: SkyActions.MSD, line: 3 },
      { action: SkyActions.AAZ, aaForce: 7, line: 3 },
      { action: SkyActions.MSD, line: 3 },
      { action: SkyActions.MSD, line: 3 },
      { action: SkyActions.N, line: 3 },
    ],
  } as Sky,
  [Sides.C]: {
    doom: [],
    science: [],
    horizon: [],
  },
});

export const Sky2: Readonly<Record<Sides, Sky>> = Object.freeze({
  [Sides.A]: {
    doom: [
      { action: DoomActions.R, amount: -1 },
      { action: DoomActions.S, amount: 1 },
      { action: DoomActions.N },
      { action: DoomActions.L },
    ],
    science: [4, 1, 3, 2],
    horizon: [
      { action: SkyActions.N, line: 0 },
      { action: SkyActions.N, line: 0 },
      { action: SkyActions.AAZ, aaForce: 4, line: 0 },
      { action: SkyActions.MR, line: 0 },
      { action: SkyActions.N, line: 0 },
      { action: SkyActions.AAZ, aaForce: 5, line: 1 },
      { action: SkyActions.N, line: 1 },
      { action: SkyActions.ML, line: 1 },
      { action: SkyActions.N, line: 1 },
      { action: SkyActions.N, line: 1 },
      { action: SkyActions.N, line: 2 },
      { action: SkyActions.MSD, line: 2 },
      { action: SkyActions.MR, line: 2 },
      { action: SkyActions.N, line: 2 },
      { action: SkyActions.AAZ, aaForce: 6, line: 2 },
      { action: SkyActions.MSD, line: 3 },
      { action: SkyActions.AAZ, aaForce: 3, line: 3 },
      { action: SkyActions.N, line: 3 },
      { action: SkyActions.AAZ, aaForce: 4, line: 3 },
      { action: SkyActions.MSD, line: 3 },
    ],
  } as Sky,
  [Sides.B]: {
    doom: [
      { action: DoomActions.D, amount: 1 },
      { action: DoomActions.N },
      { action: DoomActions.L },
    ],
    science: [3, 2, 1, 5],
    horizon: [
      { action: SkyActions.AAZ, aaForce: 6, line: 0 },
      { action: SkyActions.N, line: 0 },
      { action: SkyActions.ML, line: 0 },
      { action: SkyActions.N, line: 0 },
      { action: SkyActions.MSD, line: 0 },
      { action: SkyActions.MSD, line: 1 },
      { action: SkyActions.AAZ, aaForce: 4, line: 1 },
      { action: SkyActions.AAZ, aaForce: 7, line: 1 },
      { action: SkyActions.MR, line: 1 },
      { action: SkyActions.N, line: 1 },
      { action: SkyActions.N, line: 2 },
      { action: SkyActions.MR, line: 2 },
      { action: SkyActions.N, line: 2 },
      { action: SkyActions.MSD, line: 2 },
      { action: SkyActions.AAZ, aaForce: 7, line: 2 },
      { action: SkyActions.N, line: 3 },
      { action: SkyActions.N, line: 3 },
      { action: SkyActions.MSD, line: 3 },
      { action: SkyActions.AAZ, aaForce: 4, line: 3 },
      { action: SkyActions.N, line: 3 },
    ],
  } as Sky,
  [Sides.C]: {
    doom: [],
    science: [],
    horizon: [],
  },
});

export const Sky3: Readonly<Record<Sides, Sky>> = Object.freeze({
  [Sides.A]: {
    doom: [
      { action: DoomActions.S, amount: 1 },
      { action: DoomActions.E, amount: -1 },
      { action: DoomActions.R, amount: -1 },
      { action: DoomActions.N },
    ],
    science: [1, 6, 1, 3],
    horizon: [
      { action: SkyActions.MSD, line: 0 },
      { action: SkyActions.MR, line: 0 },
      { action: SkyActions.N, line: 0 },
      { action: SkyActions.AAZ, aaForce: 4, line: 0 },
      { action: SkyActions.N, line: 0 },
      { action: SkyActions.N, line: 1 },
      { action: SkyActions.MSD, line: 1 },
      { action: SkyActions.N, line: 1 },
      { action: SkyActions.N, line: 1 },
      { action: SkyActions.N, line: 1 },
      { action: SkyActions.AAZ, aaForce: 4, line: 2 },
      { action: SkyActions.AAZ, aaForce: 3, line: 2 },
      { action: SkyActions.N, line: 2 },
      { action: SkyActions.ML, line: 2 },
      { action: SkyActions.AAZ, aaForce: 2, line: 2 },
      { action: SkyActions.MR, line: 3 },
      { action: SkyActions.N, line: 3 },
      { action: SkyActions.AAZ, aaForce: 6, line: 3 },
      { action: SkyActions.N, line: 3 },
      { action: SkyActions.ML, line: 3 },
    ],
  } as Sky,
  [Sides.B]: {
    doom: [
      { action: DoomActions.E, amount: -3 },
      { action: DoomActions.R, amount: -2 },
      { action: DoomActions.S, amount: 2 },
      { action: DoomActions.R, amount: -1 },
    ],
    science: [2, 3, 4, 2],
    horizon: [
      { action: SkyActions.MR, line: 0 },
      { action: SkyActions.N, line: 0 },
      { action: SkyActions.AAZ, aaForce: 2, line: 0 },
      { action: SkyActions.N, line: 0 },
      { action: SkyActions.ML, line: 0 },
      { action: SkyActions.MSD, line: 1 },
      { action: SkyActions.MSD, line: 1 },
      { action: SkyActions.N, line: 1 },
      { action: SkyActions.ML, line: 1 },
      { action: SkyActions.AAZ, aaForce: 3, line: 1 },
      { action: SkyActions.AAZ, aaForce: 4, line: 2 },
      { action: SkyActions.MR, line: 2 },
      { action: SkyActions.N, line: 2 },
      { action: SkyActions.AAZ, aaForce: 5, line: 2 },
      { action: SkyActions.N, line: 2 },
      { action: SkyActions.N, line: 3 },
      { action: SkyActions.ML, line: 3 },
      { action: SkyActions.MR, line: 3 },
      { action: SkyActions.N, line: 3 },
      { action: SkyActions.MSD, line: 3 },
    ],
  } as Sky,
  [Sides.C]: {
    doom: [],
    science: [],
    horizon: [],
  },
});

export const Sky4: Readonly<Record<Sides, Sky>> = Object.freeze({
  [Sides.A]: {
    doom: [
      { action: DoomActions.S, amount: 1 },
      { action: DoomActions.E, amount: -2 },
      { action: DoomActions.S, amount: 1 },
      { action: DoomActions.N },
    ],
    science: [5, 1, 3, 11],
    horizon: [
      { action: SkyActions.N, line: 0 },
      { action: SkyActions.N, line: 0 },
      { action: SkyActions.N, line: 0 },
      { action: SkyActions.MR, line: 0 },
      { action: SkyActions.N, line: 0 },
      { action: SkyActions.N, line: 1 },
      { action: SkyActions.ML, line: 1 },
      { action: SkyActions.MR, line: 1 },
      { action: SkyActions.N, line: 1 },
      { action: SkyActions.N, line: 1 },
      { action: SkyActions.MSD, line: 2 },
      { action: SkyActions.N, line: 2 },
      { action: SkyActions.AAZ, aaForce: 1, line: 2 },
      { action: SkyActions.N, line: 2 },
      { action: SkyActions.N, line: 2 },
      { action: SkyActions.AAZ, aaForce: 2, line: 3 },
      { action: SkyActions.N, line: 3 },
      { action: SkyActions.ML, line: 3 },
      { action: SkyActions.N, line: 3 },
      { action: SkyActions.AAZ, aaForce: 4, line: 3 },
    ],
  } as Sky,
  [Sides.B]: {
    doom: [
      { action: DoomActions.E, amount: -1 },
      { action: DoomActions.S, amount: 2 },
      { action: DoomActions.E, amoint: -2 },
      { action: DoomActions.D },
    ],
    science: [3, 5, 1, 12],
    horizon: [
      { action: SkyActions.N, line: 0 },
      { action: SkyActions.AAZ, aaForce: 1, line: 0 },
      { action: SkyActions.N, line: 0 },
      { action: SkyActions.N, line: 0 },
      { action: SkyActions.N, line: 0 },
      { action: SkyActions.N, line: 1 },
      { action: SkyActions.N, line: 1 },
      { action: SkyActions.ML, line: 1 },
      { action: SkyActions.MR, line: 1 },
      { action: SkyActions.N, line: 1 },
      { action: SkyActions.MR, line: 2 },
      { action: SkyActions.N, line: 2 },
      { action: SkyActions.N, line: 2 },
      { action: SkyActions.N, line: 2 },
      { action: SkyActions.AAZ, aaForce: 2, line: 2 },
      { action: SkyActions.N, line: 3 },
      { action: SkyActions.ML, line: 3 },
      { action: SkyActions.AAZ, aaForce: 3, line: 3 },
      { action: SkyActions.MSD, line: 3 },
      { action: SkyActions.N, line: 3 },
    ],
  } as Sky,
  [Sides.C]: {
    doom: [],
    science: [],
    horizon: [],
  },
});
